language: go
install:
- go get -v github.com/gohugoio/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: H2YGR8zqtBUMq8rNoMmnuahrpkhPQ0r37DJqEZtri3pJBbVGxAApMII4iNK3J2fXPDByqoaCpcI6b3Y501B3lYZT8xp5w0S1MtIrR4pn54GaSIiM0ljWpIpo++Lt4rcHznteGcbnx3nFzMs+yw3iZusyL29qzQjOn8IU5vDXlF0Sv3djDuM0wIxcu+/hfS4EdLuNu5hdL7rPNO+VPQ2PwaKd5ZSp38BtiqMQbrfbZmCsrHl8lBRzfW8O9JykG5K/V+LoapRGRiyN9MDiYCDNtsg0iZR7HjOmD2ZPs5H0PwiDozSKimRuzhff6W9/s7XIqXZKg/00chkvDsgQm0X3z7YgCmrGYHr51JrNRYuHHryZASG4Yu1an+H/SBbI9rpUXLW9Cm0plPqduzaLk6xNTwh76AHtXtmsf4Hp93mPRVg0YMXAqrTisTeJ+C0RPomvfUbgxIPkyD4RW0iAEP9KVQ3kD/Y4CUf4pIzBhKgZZY2Hrob9GPKZoyi5EDjPlCMfbqbNYaNjCuzj8sdYoVbXdDWnO4Ne6w7YLB1A03IpA4OUDZ6zRQooFBRUhEi9k3Ga8x4suTwyCy7rTxbRpukvxN7NJIU4IVQZKwnu37UU7HxUlhob87owjKFg3RZzNtu3n4uwPb1oNxJEyeLiVos6Qd/6x33zp7jaoLw/SRsBxfc=
  - secure: Qs715bEtpMeo8Ydws1U2GDltbyCewp/xw6OnA40QAUczWnGoZ/jMbY/fVngTm8/l1OK+frfwiaGw5BpsimZ+4zwzqPrd3Q5mxUNP/07qp0rKb3QtJfvtnfJxKudBT/VGfQZnBoiYGQQ8xVL8IL/6k2nCNKLeuh2EwDcd6l6rViTC1XJH8BfhpT694bDnxgFLrfNSIRed5aYmrRvY1J/WtC7BCdgNgrbTfyH5pfFJBlv/bAUjuF34jbFt+M96D0oPrUtPJi2ziXcRlM8AnLt+e2GTSQQ43NYyNLPWQFpGG52q0OJ8Zz5On8e0iHmQhxCYrrlgUhgqA5q9zqN1KwzyyCvlZMD8jsDAzQgYQkE99AccxDrr6wF/yRkzBt56rlDp0dSEoD9JOt8YBk7y3eXseoB9R/I7YZSq475rUCGXcoOj4JyCeEX+jiaLq8Q9yWjEEYTsfEugATN6nwE2rUGxpV/yXqB/vb1G2C8vTAy2Lo325tdg1hBWKeEZds8FfpZ4fM1UT/Pu1WEjqtjtAMltv6xuJeqZeMhsmgUjJv3JVZISL9yBPQnEphAMO8YgHeP1usk+GPi/4RWncGWWKdxqOn4G81BED3pvp8NqWQ2mPmCj/UXmv3tvmf/q/wIe6kqdLGKTXJ6fxEzze+zk2xowxj+cXRmURdeTFFx23sBiq7w=
